### ISSUE TITLE
[Feature] Option to show more albums at once in Albums view

### ISSUE THREAD

**Issue by HalibutGitWiz** [owncloud/music#1184]
Albums view displays large album images (and even artist images when you have them), which is nice but also takes a lot of space. With a large library, it involves a lot of scrolling, unless you already know what you want to listen and search for it directly.

It would be nice to have an option for an alternate stylesheet that displays more albums. Here are a few ideas : 

- Smaller images (or even no image at all)
- No track list (it's a small feature loss, but I don't see any way to gain space while leaving the track list)
- Smaller fonts / spacing

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a toggle for compact view in the controller and update the layout accordingly.

You can review changes in this commit: https://github.com/mnmnk43434/owncloud-music-1184/commit/e9c15de043db0931500dd46431c52b923b714104.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by HalibutGitWiz** [comment]
I made a rough layout with custom CSS in [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)

```css
.artist-area {
    padding-top: 5px;
}

.artist-area > h1 {
    font-size: 20px;
    line-height: 20px;
}

.album-area {
    height: 50px;
    width: 450px;
    padding-top: 5px;
}

.album-area > h2 {
    padding-left: 40px;
    font-size: 16px;
}

.album-area > .albumart {
    margin-top: -50px;
    width: 30px;
    height: 30px;
    line-height: 30px;
}

.album-area ul {
    display: none;
}
```

The result is satisfactory, at least on a computer or tablet screen.

![2024-12-09_19-43](https://github.com/user-attachments/assets/00f584d4-843b-47f4-8955-f3aed895f7b5)
